#!/bin/sh

SUFFIX=""
if /sbin/iptables-compat -L | grep -q "Chain DOCKER "
then
  SUFFIX="-compat"
fi

ln -nfs "/sbin/iptables${SUFFIX}"          /usr/local/bin/iptables
ln -nfs "/sbin/iptables${SUFFIX}-save"     /usr/local/bin/iptables-save
ln -nfs "/sbin/iptables${SUFFIX}-restore"  /usr/local/bin/iptables-restore
ln -nfs "/sbin/ip6tables${SUFFIX}"         /usr/local/bin/ip6tables
ln -nfs "/sbin/ip6tables${SUFFIX}-save"    /usr/local/bin/ip6tables-save
ln -nfs "/sbin/ip6tables${SUFFIX}-restore" /usr/local/bin/ip6tables-restore
hash -r

exec /docker-ipv6nat "${@}"
