#!/bin/sh

BINARY="xtables-legacy-multi"
if iptables-nft -L | grep -q "Chain DOCKER "
then
  BINARY="xtables-nft-multi"
fi

ln -nfs "${BINARY}" /sbin/iptables
ln -nfs "${BINARY}" /sbin/iptables-save
ln -nfs "${BINARY}" /sbin/iptables-restore
ln -nfs "${BINARY}" /sbin/ip6tables
ln -nfs "${BINARY}" /sbin/ip6tables-save
ln -nfs "${BINARY}" /sbin/ip6tables-restore
hash -r

exec /docker-ipv6nat "${@}"
