FROM forumi0721/alpine-armhf-base:latest
MAINTAINER Robbert Klarenbeek <robbertkl@renbeek.nl>

RUN ["docker-build-start"]

RUN apk add --no-cache \
        ip6tables

ENV DOCKER_IPV6NAT_VERSION v0.2.0
ADD https://github.com/robbertkl/docker-ipv6nat/releases/download/${DOCKER_IPV6NAT_VERSION}/docker-ipv6nat.armhf /docker-ipv6nat
RUN chmod u+x /docker-ipv6nat

RUN ["docker-build-end"]

ENTRYPOINT ["/docker-ipv6nat"]
CMD ["--retry"]
